// Comprehensive curated science fiction book list
// Sources: Wikipedia "100 Best Novels" (1949-1984), "101 Best" (1985-2010), 
// Pre-1949 classics, complete major author bibliographies, notable non-fiction

export interface CuratedBook {
  title: string;
  author: string;
  isbn?: string;
  category: string;
  year?: number;
  reason?: string;
}

export const curatedSciFiBooks: CuratedBook[] = [
  // ===== Wikipedia "Science Fiction: The 100 Best Novels" (1949-1984) =====
  { title: "1984", author: "George Orwell", category: "Dystopian Classic", year: 1949 },
  { title: "Foundation", author: "Isaac Asimov", category: "Space Opera Classic", year: 1951 },
  { title: "I, Robot", author: "Isaac Asimov", category: "Robot Fiction", year: 1950 },
  { title: "The Demolished Man", author: "Alfred Bester", category: "Cyberpunk Precursor", year: 1953 },
  { title: "More Than Human", author: "Theodore Sturgeon", category: "Posthuman", year: 1953 },
  { title: "Childhood's End", author: "Arthur C. Clarke", category: "First Contact", year: 1953 },
  { title: "The Caves of Steel", author: "Isaac Asimov", category: "Robot Fiction", year: 1954 },
  { title: "Lord of the Flies", author: "William Golding", category: "Dystopian", year: 1954 },
  { title: "The Stars My Destination", author: "Alfred Bester", category: "Space Opera", year: 1956 },
  { title: "Double Star", author: "Robert A. Heinlein", category: "Political SF", year: 1956 },
  { title: "The Door Into Summer", author: "Robert A. Heinlein", category: "Time Travel", year: 1957 },
  { title: "The Naked Sun", author: "Isaac Asimov", category: "Robot Fiction", year: 1957 },
  { title: "A Case of Conscience", author: "James Blish", category: "Religious SF", year: 1958 },
  { title: "Have Space Suit—Will Travel", author: "Robert A. Heinlein", category: "YA Space Adventure", year: 1958 },
  { title: "A Canticle for Leibowitz", author: "Walter M. Miller Jr.", category: "Post-Apocalyptic", year: 1959 },
  { title: "Starship Troopers", author: "Robert A. Heinlein", category: "Military SF", year: 1959 },
  { title: "Stranger in a Strange Land", author: "Robert A. Heinlein", category: "Social SF", year: 1961 },
  { title: "Solaris", author: "Stanisław Lem", category: "First Contact", year: 1961 },
  { title: "The Man in the High Castle", author: "Philip K. Dick", category: "Alternate History", year: 1962 },
  { title: "A Clockwork Orange", author: "Anthony Burgess", category: "Dystopian", year: 1962 },
  { title: "Cat's Cradle", author: "Kurt Vonnegut", category: "Satirical SF", year: 1963 },
  { title: "The Drowned World", author: "J.G. Ballard", category: "Climate Fiction", year: 1962 },
  { title: "Dune", author: "Frank Herbert", category: "Space Opera Epic", year: 1965 },
  { title: "Do Androids Dream of Electric Sheep?", author: "Philip K. Dick", category: "Cyberpunk Precursor", year: 1968 },
  { title: "Stand on Zanzibar", author: "John Brunner", category: "Overpopulation", year: 1968 },
  { title: "Slaughterhouse-Five", author: "Kurt Vonnegut", category: "Time Travel", year: 1969 },
  { title: "Ubik", author: "Philip K. Dick", category: "Reality-Bending", year: 1969 },
  { title: "The Left Hand of Darkness", author: "Ursula K. Le Guin", category: "Gender Studies SF", year: 1969 },
  { title: "Tau Zero", author: "Poul Anderson", category: "Hard SF", year: 1970 },
  { title: "Ringworld", author: "Larry Niven", category: "Hard SF", year: 1970 },
  { title: "A Scanner Darkly", author: "Philip K. Dick", category: "Drug Culture SF", year: 1977 },
  { title: "The Lathe of Heaven", author: "Ursula K. Le Guin", category: "Reality-Bending", year: 1971 },
  { title: "The Word for World is Forest", author: "Ursula K. Le Guin", category: "Ecological SF", year: 1972 },
  { title: "The Gods Themselves", author: "Isaac Asimov", category: "Parallel Universes", year: 1972 },
  { title: "Rendezvous with Rama", author: "Arthur C. Clarke", category: "Hard SF", year: 1973 },
  { title: "Gravity's Rainbow", author: "Thomas Pynchon", category: "Literary SF", year: 1973 },
  { title: "The Dispossessed", author: "Ursula K. Le Guin", category: "Anarchist SF", year: 1974 },
  { title: "Flow My Tears, The Policeman Said", author: "Philip K. Dick", category: "Dystopian", year: 1974 },
  { title: "The Forever War", author: "Joe Haldeman", category: "Military SF", year: 1974 },
  { title: "Where Late the Sweet Birds Sang", author: "Kate Wilhelm", category: "Cloning", year: 1976 },
  { title: "Woman on the Edge of Time", author: "Marge Piercy", category: "Feminist SF", year: 1976 },
  { title: "Man Plus", author: "Frederik Pohl", category: "Transhumanism", year: 1976 },
  { title: "Gateway", author: "Frederik Pohl", category: "Space Exploration", year: 1977 },
  { title: "The Shockwave Rider", author: "John Brunner", category: "Cyberpunk Precursor", year: 1975 },
  { title: "The Fifth Head of Cerberus", author: "Gene Wolfe", category: "Cloning", year: 1972 },
  { title: "Roadside Picnic", author: "Arkady and Boris Strugatsky", category: "Soviet SF", year: 1972 },
  { title: "Behold the Man", author: "Michael Moorcock", category: "Time Travel", year: 1969 },
  { title: "Camp Concentration", author: "Thomas M. Disch", category: "Dystopian", year: 1968 },
  { title: "The Einstein Intersection", author: "Samuel R. Delany", category: "Mythological SF", year: 1967 },
  { title: "Babel-17", author: "Samuel R. Delany", category: "Linguistics SF", year: 1966 },
  { title: "Flowers for Algernon", author: "Daniel Keyes", category: "Posthuman", year: 1966 },
  { title: "The Three Stigmata of Palmer Eldritch", author: "Philip K. Dick", category: "Reality-Bending", year: 1965 },
  { title: "The Crystal World", author: "J.G. Ballard", category: "Catastrophe", year: 1966 },
  { title: "Rogue Moon", author: "Algis Budrys", category: "Existential SF", year: 1960 },
  { title: "The Space Merchants", author: "Frederik Pohl and C.M. Kornbluth", category: "Satirical SF", year: 1952 },
  { title: "The Jagged Orbit", author: "John Brunner", category: "Social SF", year: 1969 },
  { title: "Pavane", author: "Keith Roberts", category: "Alternate History", year: 1968 },
  { title: "The Moon is a Harsh Mistress", author: "Robert A. Heinlein", category: "Political SF", year: 1966 },
  { title: "Dhalgren", author: "Samuel R. Delany", category: "Literary SF", year: 1975 },
  { title: "Neuromancer", author: "William Gibson", category: "Cyberpunk Classic", year: 1984 },
  { title: "The Book of the New Sun", author: "Gene Wolfe", category: "Dying Earth", year: 1980 },
  { title: "Timescape", author: "Gregory Benford", category: "Hard SF", year: 1980 },
  { title: "The Female Man", author: "Joanna Russ", category: "Feminist Science Fiction", year: 1975 },
  { title: "Wild Seed", author: "Octavia E. Butler", category: "Science Fantasy", year: 1980 },
  { title: "The Sirens of Titan", author: "Kurt Vonnegut", category: "Space Opera", year: 1959 },
  { title: "Way Station", author: "Clifford D. Simak", category: "First Contact", year: 1963 },
  { title: "Crash", author: "J.G. Ballard", category: "New Wave", year: 1973 },
  { title: "High Rise", author: "J.G. Ballard", category: "Social Science Fiction", year: 1975 },
  { title: "The Wanderer", author: "Fritz Leiber", category: "Space Opera", year: 1964 },
  { title: "Nova", author: "Samuel R. Delany", category: "Space Opera", year: 1968 },
  { title: "Engine Summer", author: "John Crowley", category: "Post-Apocalyptic", year: 1979 },
  { title: "Riddley Walker", author: "Russell Hoban", category: "Post-Apocalyptic", year: 1980 },
  { title: "The Shadow of the Torturer", author: "Gene Wolfe", category: "Dying Earth", year: 1980 },

  // ===== "Science Fiction: The 101 Best Novels, 1985-2010" =====
  { title: "Galápagos", author: "Kurt Vonnegut", category: "Evolution SF", year: 1985 },
  { title: "Blood Music", author: "Greg Bear", category: "Nanotechnology", year: 1985 },
  { title: "The Postman", author: "David Brin", category: "Post-Apocalyptic", year: 1985 },
  { title: "Ender's Game", author: "Orson Scott Card", category: "Military SF", year: 1985 },
  { title: "The Handmaid's Tale", author: "Margaret Atwood", category: "Dystopian", year: 1985 },
  { title: "Speaker for the Dead", author: "Orson Scott Card", category: "Xenobiology", year: 1986 },
  { title: "The Uplift War", author: "David Brin", category: "Space Opera", year: 1987 },
  { title: "Hyperion", author: "Dan Simmons", category: "Space Opera", year: 1989 },
  { title: "The Child Garden", author: "Geoff Ryman", category: "Biopunk", year: 1989 },
  { title: "A Fire Upon the Deep", author: "Vernor Vinge", category: "Space Opera", year: 1992 },
  { title: "Red Mars", author: "Kim Stanley Robinson", category: "Mars Trilogy", year: 1992 },
  { title: "Doomsday Book", author: "Connie Willis", category: "Time Travel", year: 1992 },
  { title: "Snow Crash", author: "Neal Stephenson", category: "Cyberpunk", year: 1992 },
  { title: "The Diamond Age", author: "Neal Stephenson", category: "Nanotechnology", year: 1995 },
  { title: "The Terminal Experiment", author: "Robert J. Sawyer", category: "Consciousness Upload", year: 1995 },
  { title: "Permutation City", author: "Greg Egan", category: "Posthuman", year: 1994 },
  { title: "Beggars in Spain", author: "Nancy Kress", category: "Genetic Engineering", year: 1993 },
  { title: "Parable of the Sower", author: "Octavia E. Butler", category: "Dystopian", year: 1993 },
  { title: "The Sparrow", author: "Mary Doria Russell", category: "First Contact", year: 1996 },
  { title: "Anathem", author: "Neal Stephenson", category: "Philosophical SF", year: 2008 },
  { title: "Blindsight", author: "Peter Watts", category: "First Contact", year: 2006 },
  { title: "Accelerando", author: "Charles Stross", category: "Singularity", year: 2005 },
  { title: "Old Man's War", author: "John Scalzi", category: "Military SF", year: 2005 },
  { title: "Spin", author: "Robert Charles Wilson", category: "Time Dilation", year: 2005 },
  { title: "Rainbow's End", author: "Vernor Vinge", category: "Near Future", year: 2006 },
  { title: "The Road", author: "Cormac McCarthy", category: "Post-Apocalyptic", year: 2006 },
  { title: "Brasyl", author: "Ian McDonald", category: "Multiverse", year: 2007 },
  { title: "The Yiddish Policemen's Union", author: "Michael Chabon", category: "Alternate History", year: 2007 },
  { title: "Cryptonomicon", author: "Neal Stephenson", category: "Cryptography", year: 1999 },
  { title: "A Deepness in the Sky", author: "Vernor Vinge", category: "Space Opera", year: 1999 },
  { title: "Forever Peace", author: "Joe Haldeman", category: "Military SF", year: 1997 },
  { title: "Blue Mars", author: "Kim Stanley Robinson", category: "Mars Trilogy", year: 1996 },
  { title: "Green Mars", author: "Kim Stanley Robinson", category: "Mars Trilogy", year: 1993 },
  { title: "Distraction", author: "Bruce Sterling", category: "Political SF", year: 1998 },
  { title: "Forever Free", author: "Joe Haldeman", category: "Military SF", year: 1999 },
  { title: "The Quantum Rose", author: "Catherine Asaro", category: "Space Opera", year: 2000 },
  { title: "Darwin's Radio", author: "Greg Bear", category: "Evolutionary SF", year: 1999 },
  { title: "Calculating God", author: "Robert J. Sawyer", category: "Hard SF", year: 2000 },
  { title: "Perdido Street Station", author: "China Miéville", category: "New Weird", year: 2000 },
  { title: "The Chronoliths", author: "Robert Charles Wilson", category: "Time Anomalies", year: 2001 },
  { title: "Passage", author: "Connie Willis", category: "Near Death Experience", year: 2001 },
  { title: "The Years of Rice and Salt", author: "Kim Stanley Robinson", category: "Alternate History", year: 2002 },
  { title: "Kiln People", author: "David Brin", category: "Identity", year: 2002 },
  { title: "Ilium", author: "Dan Simmons", category: "Mythology SF", year: 2003 },
  { title: "The Algebraist", author: "Iain M. Banks", category: "Space Opera", year: 2004 },
  { title: "River of Gods", author: "Ian McDonald", category: "AI", year: 2004 },
  { title: "Market Forces", author: "Richard K. Morgan", category: "Corporate Warfare", year: 2004 },
  { title: "Iron Sunrise", author: "Charles Stross", category: "Space Opera", year: 2004 },
  { title: "Olympos", author: "Dan Simmons", category: "Mythology SF", year: 2005 },
  { title: "Air", author: "Geoff Ryman", category: "Near Future", year: 2005 },
  { title: "Glasshouse", author: "Charles Stross", category: "Posthuman", year: 2006 },
  { title: "Rollback", author: "Robert J. Sawyer", category: "Life Extension", year: 2007 },
  { title: "The Last Colony", author: "John Scalzi", category: "Military SF", year: 2007 },
  { title: "Making Money", author: "Terry Pratchett", category: "Satirical SF", year: 2007 },
  { title: "Halting State", author: "Charles Stross", category: "Near Future", year: 2007 },
  { title: "Marsbound", author: "Joe Haldeman", category: "Mars Fiction", year: 2008 },
  { title: "Little Brother", author: "Cory Doctorow", category: "YA Dystopian", year: 2008 },
  { title: "Saturn's Children", author: "Charles Stross", category: "Robot Fiction", year: 2008 },
  { title: "The Graveyard Book", author: "Neil Gaiman", category: "Urban Fantasy", year: 2008 },
  { title: "Cryoburn", author: "Lois McMaster Bujold", category: "Space Opera", year: 2010 },
  { title: "The Windup Girl", author: "Paolo Bacigalupi", category: "Biopunk", year: 2009 },
  { title: "Boneshaker", author: "Cherie Priest", category: "Steampunk", year: 2009 },
  { title: "The City & The City", author: "China Miéville", category: "New Weird", year: 2009 },
  { title: "Julian Comstock", author: "Robert Charles Wilson", category: "Post-Apocalyptic", year: 2009 },
  { title: "Palimpsest", author: "Catherynne M. Valente", category: "Urban Fantasy", year: 2009 },
  { title: "Wake", author: "Robert J. Sawyer", category: "AI", year: 2009 },
  { title: "Galileo's Dream", author: "Kim Stanley Robinson", category: "Time Travel", year: 2009 },

  // ===== Pre-1949 Classics =====
  { title: "Frankenstein", author: "Mary Shelley", category: "Gothic SF", year: 1818 },
  { title: "Twenty Thousand Leagues Under the Sea", author: "Jules Verne", category: "Adventure SF", year: 1870 },
  { title: "Journey to the Center of the Earth", author: "Jules Verne", category: "Adventure SF", year: 1864 },
  { title: "From the Earth to the Moon", author: "Jules Verne", category: "Space Travel", year: 1865 },
  { title: "The Time Machine", author: "H.G. Wells", category: "Time Travel Classic", year: 1895 },
  { title: "The War of the Worlds", author: "H.G. Wells", category: "Invasion SF", year: 1898 },
  { title: "The Island of Doctor Moreau", author: "H.G. Wells", category: "Mad Scientist", year: 1896 },
  { title: "The Invisible Man", author: "H.G. Wells", category: "Mad Scientist", year: 1897 },
  { title: "We", author: "Yevgeny Zamyatin", category: "Dystopian Classic", year: 1924 },
  { title: "Brave New World", author: "Aldous Huxley", category: "Dystopian Classic", year: 1932 },
  { title: "Last and First Men", author: "Olaf Stapledon", category: "Future History", year: 1930 },
  { title: "Star Maker", author: "Olaf Stapledon", category: "Cosmology", year: 1937 },
  { title: "The Skylark of Space", author: "E.E. 'Doc' Smith", category: "Space Opera Classic", year: 1928 },
  { title: "Triplanetary", author: "E.E. 'Doc' Smith", category: "Space Opera Classic", year: 1934 },
  { title: "Slan", author: "A.E. van Vogt", category: "Superhuman", year: 1940 },
  { title: "The Weapon Shops of Isher", author: "A.E. van Vogt", category: "Space Opera", year: 1941 },

  // ===== Complete Philip K. Dick Bibliography =====
  { title: "Solar Lottery", author: "Philip K. Dick", category: "Political SF", year: 1955 },
  { title: "The World Jones Made", author: "Philip K. Dick", category: "Precognition", year: 1956 },
  { title: "Eye in the Sky", author: "Philip K. Dick", category: "Alternate Reality", year: 1957 },
  { title: "The Cosmic Puppets", author: "Philip K. Dick", category: "Metaphysical", year: 1957 },
  { title: "The Variable Man", author: "Philip K. Dick", category: "Space Opera", year: 1953 },
  { title: "Dr. Futurity", author: "Philip K. Dick", category: "Time Travel", year: 1960 },
  { title: "Vulcan's Hammer", author: "Philip K. Dick", category: "AI", year: 1960 },
  { title: "The Man Who Japed", author: "Philip K. Dick", category: "Dystopian", year: 1956 },
  { title: "Time Out of Joint", author: "Philip K. Dick", category: "Reality-Bending", year: 1959 },
  { title: "Martian Time-Slip", author: "Philip K. Dick", category: "Mars Fiction", year: 1964 },
  { title: "Dr. Bloodmoney", author: "Philip K. Dick", category: "Post-Apocalyptic", year: 1965 },
  { title: "The Crack in Space", author: "Philip K. Dick", category: "Parallel Worlds", year: 1966 },
  { title: "The Zap Gun", author: "Philip K. Dick", category: "Arms Race", year: 1967 },
  { title: "The Ganymede Takeover", author: "Philip K. Dick", category: "Invasion", year: 1967 },
  { title: "Counter-Clock World", author: "Philip K. Dick", category: "Time Reversal", year: 1967 },
  { title: "The Penultimate Truth", author: "Philip K. Dick", category: "Dystopian", year: 1964 },
  { title: "The Simulacra", author: "Philip K. Dick", category: "Political SF", year: 1964 },
  { title: "Now Wait for Last Year", author: "Philip K. Dick", category: "Alternate Realities", year: 1966 },
  { title: "Galactic Pot-Healer", author: "Philip K. Dick", category: "Metaphysical SF", year: 1969 },
  { title: "We Can Build You", author: "Philip K. Dick", category: "Robot Fiction", year: 1972 },
  { title: "Our Friends from Frolix 8", author: "Philip K. Dick", category: "Space Opera", year: 1970 },
  { title: "A Maze of Death", author: "Philip K. Dick", category: "Theological SF", year: 1970 },
  { title: "VALIS", author: "Philip K. Dick", category: "Metaphysical", year: 1981 },
  { title: "The Divine Invasion", author: "Philip K. Dick", category: "Theological SF", year: 1981 },
  { title: "The Transmigration of Timothy Archer", author: "Philip K. Dick", category: "Literary SF", year: 1982 },
  { title: "Lies, Inc.", author: "Philip K. Dick", category: "Conspiracy", year: 1984 },
  { title: "Clans of the Alphane Moon", author: "Philip K. Dick", category: "Mental Illness", year: 1964 },
  { title: "The Unteleported Man", author: "Philip K. Dick", category: "Space Colonization", year: 1966 },

  // ===== Additional Isaac Asimov =====
  { title: "Foundation and Empire", author: "Isaac Asimov", category: "Space Opera", year: 1952 },
  { title: "Second Foundation", author: "Isaac Asimov", category: "Space Opera", year: 1953 },
  { title: "Foundation's Edge", author: "Isaac Asimov", category: "Space Opera", year: 1982 },
  { title: "Foundation and Earth", author: "Isaac Asimov", category: "Space Opera", year: 1986 },
  { title: "Prelude to Foundation", author: "Isaac Asimov", category: "Space Opera", year: 1988 },
  { title: "Forward the Foundation", author: "Isaac Asimov", category: "Space Opera", year: 1993 },
  { title: "The Robots of Dawn", author: "Isaac Asimov", category: "Robot Fiction", year: 1983 },
  { title: "Robots and Empire", author: "Isaac Asimov", category: "Robot Fiction", year: 1985 },
  { title: "Nemesis", author: "Isaac Asimov", category: "Space Opera", year: 1989 },
  { title: "Nightfall", author: "Isaac Asimov", category: "Classic Novella", year: 1990 },
  { title: "The End of Eternity", author: "Isaac Asimov", category: "Time Travel", year: 1955 },

  // ===== Additional Ursula K. Le Guin =====
  { title: "A Wizard of Earthsea", author: "Ursula K. Le Guin", category: "Fantasy", year: 1968 },
  { title: "The Tombs of Atuan", author: "Ursula K. Le Guin", category: "Fantasy", year: 1970 },
  { title: "The Farthest Shore", author: "Ursula K. Le Guin", category: "Fantasy", year: 1972 },
  { title: "Tehanu", author: "Ursula K. Le Guin", category: "Fantasy", year: 1990 },
  { title: "The Telling", author: "Ursula K. Le Guin", category: "Anthropological SF", year: 2000 },
  { title: "Four Ways to Forgiveness", author: "Ursula K. Le Guin", category: "Social SF", year: 1995 },
  { title: "Always Coming Home", author: "Ursula K. Le Guin", category: "Anthropological SF", year: 1985 },

  // ===== Additional Arthur C. Clarke =====
  { title: "2001: A Space Odyssey", author: "Arthur C. Clarke", category: "Hard SF Classic", year: 1968 },
  { title: "The City and the Stars", author: "Arthur C. Clarke", category: "Far Future", year: 1956 },
  { title: "The Fountains of Paradise", author: "Arthur C. Clarke", category: "Space Elevator", year: 1979 },

  // ===== Additional Robert A. Heinlein =====
  { title: "Time Enough for Love", author: "Robert A. Heinlein", category: "Time Travel", year: 1973 },
  { title: "The Number of the Beast", author: "Robert A. Heinlein", category: "Multiverse", year: 1980 },
  { title: "Job: A Comedy of Justice", author: "Robert A. Heinlein", category: "Religious SF", year: 1984 },

  // ===== Additional Ray Bradbury =====
  { title: "The Martian Chronicles", author: "Ray Bradbury", category: "Mars Fiction", year: 1950 },
  { title: "Fahrenheit 451", author: "Ray Bradbury", category: "Dystopian Classic", year: 1953 },
  { title: "Something Wicked This Way Comes", author: "Ray Bradbury", category: "Dark Fantasy", year: 1962 },
  { title: "The Illustrated Man", author: "Ray Bradbury", category: "Short Stories", year: 1951 },

  // ===== Contemporary Excellence (2011-2025) =====
  { title: "The Three-Body Problem", author: "Liu Cixin", category: "Hard SF", year: 2008 },
  { title: "Ancillary Justice", author: "Ann Leckie", category: "Space Opera", year: 2013 },
  { title: "The Fifth Season", author: "N.K. Jemisin", category: "Apocalyptic Fantasy", year: 2015 },
  { title: "The Martian", author: "Andy Weir", category: "Hard SF", year: 2011 },
  { title: "Seveneves", author: "Neal Stephenson", category: "Hard SF", year: 2015 },
  { title: "The Long Way to a Small, Angry Planet", author: "Becky Chambers", category: "Cozy Space Opera", year: 2014 },
  { title: "The Expanse: Leviathan Wakes", author: "James S.A. Corey", category: "Space Opera", year: 2011 },
  { title: "This Is How You Lose the Time War", author: "Amal El-Mohtar and Max Gladstone", category: "Time Travel Romance", year: 2019 },
  { title: "The Power", author: "Naomi Alderman", category: "Feminist SF", year: 2016 },
  { title: "Children of Time", author: "Adrian Tchaikovsky", category: "Evolution SF", year: 2015 },
  { title: "Project Hail Mary", author: "Andy Weir", category: "Hard SF", year: 2021 },
  { title: "Gideon the Ninth", author: "Tamsyn Muir", category: "Space Fantasy", year: 2019 },
  { title: "A Memory Called Empire", author: "Arkady Martine", category: "Space Opera", year: 2019 },
  { title: "Network Effect", author: "Martha Wells", category: "AI Fiction", year: 2020 },
  { title: "Light from Uncommon Stars", author: "Ryka Aoki", category: "Contemporary SF", year: 2021 },
  { title: "Station Eleven", author: "Emily St. John Mandel", category: "Post-Apocalyptic", year: 2014 },
  { title: "Klara and the Sun", author: "Kazuo Ishiguro", category: "AI Fiction", year: 2021 },
  { title: "The Ministry for the Future", author: "Kim Stanley Robinson", category: "Climate Fiction", year: 2020 },
  { title: "Annihilation", author: "Jeff VanderMeer", category: "New Weird", year: 2014 },
  { title: "Embassytown", author: "China Miéville", category: "Linguistic Science Fiction", year: 2011 },
  { title: "Diaspora", author: "Greg Egan", category: "Hard Science Fiction", year: 1997 },

  // ===== Goodreads Best Science Fiction Additions =====
  // Douglas Adams Collection
  { title: "The Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", category: "Comedic SF", year: 1979 },
  { title: "The Restaurant at the End of the Universe", author: "Douglas Adams", category: "Comedic SF", year: 1980 },
  { title: "Life, the Universe and Everything", author: "Douglas Adams", category: "Comedic SF", year: 1982 },
  { title: "So Long, and Thanks for All the Fish", author: "Douglas Adams", category: "Comedic SF", year: 1984 },
  { title: "Mostly Harmless", author: "Douglas Adams", category: "Comedic SF", year: 1992 },
  { title: "Dirk Gently's Holistic Detective Agency", author: "Douglas Adams", category: "Comedic SF", year: 1987 },
  { title: "The Long Dark Tea-Time of the Soul", author: "Douglas Adams", category: "Comedic SF", year: 1988 },
  
  // Contemporary Bestsellers
  { title: "Ready Player One", author: "Ernest Cline", category: "Virtual Reality", year: 2011 },
  { title: "Ready Player Two", author: "Ernest Cline", category: "Virtual Reality", year: 2020 },
  { title: "Armada", author: "Ernest Cline", category: "Alien Invasion", year: 2015 },
  { title: "The Hunger Games", author: "Suzanne Collins", category: "YA Dystopian", year: 2008 },
  { title: "Catching Fire", author: "Suzanne Collins", category: "YA Dystopian", year: 2009 },
  { title: "Mockingjay", author: "Suzanne Collins", category: "YA Dystopian", year: 2010 },
  { title: "Dark Matter", author: "Blake Crouch", category: "Multiverse Thriller", year: 2016 },
  { title: "Recursion", author: "Blake Crouch", category: "Memory SF", year: 2019 },
  { title: "Upgrade", author: "Blake Crouch", category: "Genetic Engineering", year: 2022 },
  
  // Michael Crichton Collection
  { title: "Jurassic Park", author: "Michael Crichton", category: "Techno-Thriller", year: 1990 },
  { title: "The Lost World", author: "Michael Crichton", category: "Techno-Thriller", year: 1995 },
  { title: "Sphere", author: "Michael Crichton", category: "First Contact", year: 1987 },
  { title: "Timeline", author: "Michael Crichton", category: "Time Travel", year: 1999 },
  { title: "Prey", author: "Michael Crichton", category: "Nanotechnology", year: 2002 },
  { title: "The Andromeda Strain", author: "Michael Crichton", category: "Techno-Thriller", year: 1969 },
  { title: "Congo", author: "Michael Crichton", category: "Techno-Thriller", year: 1980 },
  { title: "Eaters of the Dead", author: "Michael Crichton", category: "Historical SF", year: 1976 },
  { title: "Next", author: "Michael Crichton", category: "Genetic Engineering", year: 2006 },
  
  // Carl Sagan
  { title: "Contact", author: "Carl Sagan", category: "First Contact", year: 1985 },
  
  // Additional Award Winners
  { title: "A Wrinkle in Time", author: "Madeleine L'Engle", category: "YA SF", year: 1962 },
  { title: "A Wind in the Door", author: "Madeleine L'Engle", category: "YA SF", year: 1973 },
  { title: "A Swiftly Tilting Planet", author: "Madeleine L'Engle", category: "YA SF", year: 1978 },
  { title: "Ender's Shadow", author: "Orson Scott Card", category: "Military SF", year: 1999 },
  { title: "Xenocide", author: "Orson Scott Card", category: "Xenobiology", year: 1991 },
  { title: "Children of the Mind", author: "Orson Scott Card", category: "Xenobiology", year: 1996 },
  { title: "Piranesi", author: "Susanna Clarke", category: "Surrealist Fiction", year: 2020 },
  { title: "Jonathan Strange & Mr Norrell", author: "Susanna Clarke", category: "Historical Fantasy", year: 2004 },
  
  // Ted Chiang Short Story Collections
  { title: "Stories of Your Life and Others", author: "Ted Chiang", category: "Short Stories", year: 2002 },
  { title: "Exhalation: Stories", author: "Ted Chiang", category: "Short Stories", year: 2019 },
  
  // Murderbot Diaries
  { title: "All Systems Red", author: "Martha Wells", category: "AI Fiction", year: 2017 },
  { title: "Artificial Condition", author: "Martha Wells", category: "AI Fiction", year: 2018 },
  { title: "Rogue Protocol", author: "Martha Wells", category: "AI Fiction", year: 2018 },
  { title: "Exit Strategy", author: "Martha Wells", category: "AI Fiction", year: 2018 },
  { title: "Fugitive Telemetry", author: "Martha Wells", category: "AI Fiction", year: 2021 },
  
  // R.F. Kuang
  { title: "Babel", author: "R.F. Kuang", category: "Historical Fantasy", year: 2022 },
  { title: "The Poppy War", author: "R.F. Kuang", category: "Military Fantasy", year: 2018 },
  
  // Additional Popular SF
  { title: "The Time Traveler's Wife", author: "Audrey Niffenegger", category: "Time Travel Romance", year: 2003 },
  { title: "Never Let Me Go", author: "Kazuo Ishiguro", category: "Dystopian", year: 2005 },
  { title: "I, Robot", author: "Isaac Asimov", category: "Robot Fiction", year: 1950 },
  { title: "11/22/63", author: "Stephen King", category: "Time Travel", year: 2011 },
  { title: "The Stand", author: "Stephen King", category: "Post-Apocalyptic", year: 1978 },
  { title: "Fahrenheit 451", author: "Ray Bradbury", category: "Dystopian Classic", year: 1953 },
  { title: "World War Z", author: "Max Brooks", category: "Post-Apocalyptic", year: 2006 },
  { title: "The Giver", author: "Lois Lowry", category: "YA Dystopian", year: 1993 },
  { title: "Flowers for Algernon", author: "Daniel Keyes", category: "Posthuman", year: 1966 },
  { title: "I Am Legend", author: "Richard Matheson", category: "Post-Apocalyptic", year: 1954 },
  { title: "The Host", author: "Stephenie Meyer", category: "Alien Invasion", year: 2008 },
  { title: "2001: A Space Odyssey", author: "Arthur C. Clarke", category: "Hard SF Classic", year: 1968 },
  { title: "The Sirens of Titan", author: "Kurt Vonnegut", category: "Space Opera", year: 1959 },
  { title: "Cat's Cradle", author: "Kurt Vonnegut", category: "Satirical SF", year: 1963 },
  { title: "Oryx and Crake", author: "Margaret Atwood", category: "Dystopian", year: 2003 },
  { title: "The Year of the Flood", author: "Margaret Atwood", category: "Dystopian", year: 2009 },
  { title: "MaddAddam", author: "Margaret Atwood", category: "Dystopian", year: 2013 },
  
  // Red Rising Series
  { title: "Red Rising", author: "Pierce Brown", category: "Dystopian", year: 2014 },
  { title: "Golden Son", author: "Pierce Brown", category: "Dystopian", year: 2015 },
  { title: "Morning Star", author: "Pierce Brown", category: "Dystopian", year: 2016 },
  
  // Remembrance of Earth's Past Trilogy (Liu Cixin)
  { title: "The Dark Forest", author: "Liu Cixin", category: "Hard SF", year: 2008 },
  { title: "Death's End", author: "Liu Cixin", category: "Hard SF", year: 2010 },
  
  // More Contemporary Favorites
  { title: "Wool", author: "Hugh Howey", category: "Post-Apocalyptic", year: 2011 },
  { title: "Shift", author: "Hugh Howey", category: "Post-Apocalyptic", year: 2013 },
  { title: "Dust", author: "Hugh Howey", category: "Post-Apocalyptic", year: 2013 },
  { title: "The Girl with All the Gifts", author: "M.R. Carey", category: "Post-Apocalyptic", year: 2014 },
  { title: "Sea of Rust", author: "C. Robert Cargill", category: "AI Fiction", year: 2017 },
  { title: "An Absolutely Remarkable Thing", author: "Hank Green", category: "First Contact", year: 2018 },
  { title: "A Beautifully Foolish Endeavor", author: "Hank Green", category: "First Contact", year: 2020 },

  // ===== Notable Non-Fiction =====
  { title: "Sapiens: A Brief History of Humankind", author: "Yuval Noah Harari", category: "Popular Science Non-Fiction", year: 2011 },
  { title: "Homo Deus: A Brief History of Tomorrow", author: "Yuval Noah Harari", category: "Futurism Non-Fiction", year: 2015 },
  { title: "Life 3.0: Being Human in the Age of Artificial Intelligence", author: "Max Tegmark", category: "AI Non-Fiction", year: 2017 },
  { title: "The Singularity Is Near", author: "Ray Kurzweil", category: "Futurism Non-Fiction", year: 2005 },
  { title: "Superintelligence: Paths, Dangers, Strategies", author: "Nick Bostrom", category: "AI Safety Non-Fiction", year: 2014 },
  { title: "The Vital Question", author: "Nick Lane", category: "Biology Non-Fiction", year: 2015 },
  { title: "The Gene: An Intimate History", author: "Siddhartha Mukherjee", category: "Biology Non-Fiction", year: 2016 },
  { title: "Cosmos", author: "Carl Sagan", category: "Astronomy Non-Fiction", year: 1980 },
  { title: "A Brief History of Time", author: "Stephen Hawking", category: "Physics Non-Fiction", year: 1988 },
  { title: "The Selfish Gene", author: "Richard Dawkins", category: "Evolution Non-Fiction", year: 1976 },
  { title: "Gödel, Escher, Bach: An Eternal Golden Braid", author: "Douglas Hofstadter", category: "Cognitive Science Non-Fiction", year: 1979 },
  { title: "The Information: A History, a Theory, a Flood", author: "James Gleick", category: "Information Theory Non-Fiction", year: 2011 },
  { title: "The Structure of Scientific Revolutions", author: "Thomas Kuhn", category: "Philosophy of Science Non-Fiction", year: 1962 },
  { title: "The Emperor of All Maladies", author: "Siddhartha Mukherjee", category: "Medical History Non-Fiction", year: 2010 },
  { title: "How We Got to Now", author: "Steven Johnson", category: "Innovation History Non-Fiction", year: 2014 },
  { title: "The Demon-Haunted World", author: "Carl Sagan", category: "Science", year: 1995 },
  { title: "The Sixth Extinction", author: "Elizabeth Kolbert", category: "Environmental Science", year: 2014 },
  { title: "The Innovators", author: "Walter Isaacson", category: "Technology History", year: 2014 },
  { title: "Weapons of Math Destruction", author: "Cathy O'Neil", category: "Data Science", year: 2016 },
  { title: "The Signal and the Noise", author: "Nate Silver", category: "Statistics", year: 2012 },
  { title: "Behave", author: "Robert Sapolsky", category: "Neuroscience", year: 2017 },
];

// Get random selection of curated books
export const getRandomCuratedBooks = (count: number = 12): CuratedBook[] => {
  const shuffled = [...curatedSciFiBooks].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};

// Get books by category
export const getCuratedBooksByCategory = (category: string, count: number = 8): CuratedBook[] => {
  const filtered = curatedSciFiBooks.filter(
    book => book.category.toLowerCase().includes(category.toLowerCase())
  );
  const shuffled = [...filtered].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
};

// Get a mixed selection
export const getMixedBookSelection = (curatedCount: number = 6): CuratedBook[] => {
  return getRandomCuratedBooks(curatedCount);
};
